name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - uses: rojo-rbx/setup-foreman@1.0.0
      name: Download Foreman
      with:
          token: $(( secrets.GITHUB_TOKEN ))

    - name: Run Selene on src
      run: selene src

  style:
    name: Style
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
   
    - uses: rojo-rbx/setup-foreman@1.0.0
      name: Download Foreman
      with:
          token: $(( secrets.GITHUB_TOKEN ))

    - name: Run StyLua on src
      run: stylua src --check
